import random

qa_db = {
    "python": {
        "easy": [
            ("What is Python? What are its key features?",
             "Python is a high-level, interpreted, dynamically-typed language known for simple, readable syntax. Key features: dynamic typing, automatic memory management, extensive standard library, support for OOP/functional/procedural paradigms, and cross-platform compatibility."),
            ("What is the difference between a list and a tuple?",
             "Lists are mutable (can be changed after creation) and defined with []. Tuples are immutable (cannot be changed) and defined with (). Tuples are faster and used for fixed data; lists are used when data needs to change."),
            ("What is a dictionary in Python?",
             "A dictionary is an unordered collection of key-value pairs defined with {}. Keys must be unique and immutable. Access values with d['key']. Example: {'name': 'Alice', 'age': 25}. Supports O(1) average-case lookups."),
            ("What are Python data types?",
             "Built-in types: int, float, complex (numeric); str (text); list, tuple (sequences); set, frozenset; dict (mapping); bool; None; bytes/bytearray. Everything in Python is an object."),
            ("What is the difference between '==' and 'is' in Python?",
             "'==' checks value equality — do two objects have the same value? 'is' checks identity — do two variables point to the exact same object in memory? Example: [1,2] == [1,2] is True, but [1,2] is [1,2] is False."),
        ],
        "medium": [
            ("What is Python GIL and why does it matter?",
             "The Global Interpreter Lock (GIL) is a mutex in CPython allowing only one thread to execute Python bytecode at a time. It prevents true CPU parallelism with threads. For CPU-bound tasks use multiprocessing; for I/O-bound tasks threading still helps since I/O releases the GIL."),
            ("What are decorators in Python? Give an example.",
             "Decorators are functions that wrap another function to extend behavior without modifying it. Syntax: @decorator_name above a function definition. Example: @staticmethod, @classmethod, or custom: a @timer decorator measures execution time by wrapping the function call with time.time() checks."),
            ("What is the difference between deep copy and shallow copy?",
             "Shallow copy (copy.copy()) creates a new object but nested objects still share references with the original. Deep copy (copy.deepcopy()) recursively copies everything — nested objects get fully independent copies. Use deep copy when you don't want changes in the copy to affect the original."),
            ("Explain list comprehension with an example.",
             "List comprehension creates a new list concisely: [expression for item in iterable if condition]. Example: squares = [x**2 for x in range(10) if x % 2 == 0] produces [0, 4, 16, 36, 64]. Faster and more readable than equivalent for-loops."),
            ("What are *args and **kwargs in Python?",
             "*args collects extra positional arguments into a tuple inside the function. **kwargs collects extra keyword arguments into a dictionary. They enable flexible function signatures. Example: def f(*args, **kwargs) can accept any combination of arguments."),
        ],
        "hard": [
            ("Explain Python's memory management and garbage collection.",
             "Python uses reference counting as primary strategy — each object tracks how many references point to it; when count hits 0 memory is freed. A cyclic garbage collector handles reference cycles that reference counting misses. Memory lives in a private heap managed by CPython's allocator."),
            ("What are metaclasses in Python?",
             "A metaclass is a class of a class — its instances are classes rather than objects. The default metaclass is 'type'. Metaclasses let you customize class creation: add methods, enforce constraints, register subclasses. Used heavily in frameworks like Django ORM and SQLAlchemy."),
            ("Explain the difference between multiprocessing and multithreading in Python.",
             "Multithreading runs multiple threads in the same process sharing memory, but the GIL limits CPU parallelism — good for I/O-bound tasks. Multiprocessing spawns separate processes with own memory space, achieving true CPU parallelism — good for CPU-bound tasks but higher memory overhead and IPC complexity."),
            ("What is a context manager and how do you create one?",
             "Context managers handle setup and teardown around a block of code using the 'with' statement. Implement __enter__ (setup) and __exit__ (teardown/cleanup) in a class, or use the @contextmanager decorator with a generator. Example: with open('file.txt') as f — guarantees file is closed even if an exception occurs."),
            ("Explain Python's MRO (Method Resolution Order).",
             "MRO defines the order Python searches for methods/attributes in class hierarchies during inheritance. Uses the C3 linearization algorithm: searches left to right, depth first, respecting base class order. Inspect with ClassName.__mro__ or ClassName.mro(). Prevents the diamond problem in multiple inheritance."),
        ],
    },

    "java": {
        "easy": [
            ("What is the difference between JDK, JRE, and JVM?",
             "JVM (Java Virtual Machine) runs bytecode and is platform-specific. JRE (Java Runtime Environment) = JVM + standard libraries — needed to run Java programs. JDK (Java Development Kit) = JRE + compiler (javac) + development tools — needed to develop Java programs."),
            ("What are the primitive data types in Java?",
             "Java has 8 primitives: byte (8-bit), short (16-bit), int (32-bit), long (64-bit), float (32-bit decimal), double (64-bit decimal), char (16-bit Unicode character), boolean (true/false). Unlike objects, primitives are stored directly on the stack."),
            ("What is the difference between == and .equals() in Java?",
             "== compares references (memory addresses) for objects — checks if two variables point to the same object. .equals() compares content/value. For String: 'hello' == 'hello' may be false if different objects, but 'hello'.equals('hello') is always true."),
            ("What is a constructor in Java?",
             "A constructor is a special method called when an object is created (new keyword). It has the same name as the class, no return type. Used to initialize object state. Java provides a default no-arg constructor if none is defined. Constructors can be overloaded."),
            ("What is the difference between String, StringBuilder, and StringBuffer?",
             "String is immutable — each operation creates a new object, inefficient for many changes. StringBuilder is mutable and fast but not thread-safe. StringBuffer is mutable and thread-safe (synchronized methods) but slower. Use StringBuilder for single-threaded string manipulation."),
        ],
        "medium": [
            ("What is the difference between abstract class and interface in Java?",
             "Abstract class can have concrete methods, constructors, instance variables, and state — a class can extend only one. Interface (pre-Java 8) only had abstract methods; now can have default/static methods — a class can implement multiple interfaces. Use abstract class for shared code; interface for capability contracts."),
            ("Explain exception handling in Java with try, catch, finally.",
             "try block contains code that might throw an exception. catch block handles specific exception types — multiple catch blocks allowed. finally block always executes regardless of exception — used for cleanup (closing resources). Java 7+ added try-with-resources for auto-closing."),
            ("What is method overloading and method overriding?",
             "Overloading: same method name, different parameter types/count in the same class — resolved at compile time (static polymorphism). Overriding: subclass provides its own implementation of an inherited method with same signature — resolved at runtime (dynamic polymorphism). @Override annotation helps catch errors."),
            ("What are generics in Java?",
             "Generics allow classes/methods to work with any type specified at compile time, providing type safety without casting. Example: List<String> ensures only Strings are added. Type parameters (<T>, <K,V>) are erased at runtime (type erasure). Prevents ClassCastException at runtime."),
            ("What is the Collections framework in Java?",
             "The Collections framework provides reusable data structures and algorithms. Key interfaces: List (ArrayList, LinkedList), Set (HashSet, TreeSet), Map (HashMap, TreeMap), Queue (PriorityQueue). The Collections utility class provides sorting, searching, and synchronization helpers."),
        ],
        "hard": [
            ("Explain Java memory model and how garbage collection works.",
             "JVM memory: Heap (objects, GC-managed), Stack (method frames, primitives), Metaspace (class metadata), PC register, native method stack. GC algorithms: Serial, Parallel, G1 (default in Java 9+), ZGC. GC uses generational collection — Young Gen (Eden+Survivor) and Old Gen — based on the weak generational hypothesis."),
            ("What are Java streams and how do they work?",
             "Streams (Java 8+) provide a declarative pipeline for processing collections. Operations: intermediate (filter, map, sorted — lazy, return Stream) and terminal (collect, forEach, reduce — trigger execution). Streams don't modify the source, support parallelism with parallelStream(), and process elements lazily."),
            ("Explain the SOLID principles with Java examples.",
             "S: Single Responsibility — one class, one reason to change. O: Open/Closed — open for extension, closed for modification (use interfaces). L: Liskov Substitution — subclasses must be substitutable for base class. I: Interface Segregation — small focused interfaces. D: Dependency Inversion — depend on abstractions not concretions."),
            ("What is the difference between Callable and Runnable?",
             "Runnable.run() returns void and cannot throw checked exceptions — used with Thread or ExecutorService. Callable.call() returns a value (wrapped in Future) and can throw checked exceptions. Use Callable when you need a result from an async task; use Runnable for fire-and-forget tasks."),
            ("Explain Java concurrency utilities (ExecutorService, Future, etc.).",
             "ExecutorService manages a thread pool — submit tasks with submit() (returns Future) or execute() (Runnable). Future represents a pending result — get() blocks until done. CompletableFuture enables chaining async operations. CountDownLatch, CyclicBarrier for thread coordination. ConcurrentHashMap for thread-safe maps."),
        ],
    },

    "c": {
        "easy": [
            ("What is a pointer in C?",
             "A pointer is a variable that stores the memory address of another variable. Declared with *: int *p = &x; stores address of x. Dereference with *p to access the value. Pointers enable dynamic memory allocation, arrays, and passing by reference."),
            ("What is the difference between malloc() and calloc()?",
             "malloc(size) allocates a block of 'size' bytes but leaves memory uninitialized (contains garbage values). calloc(n, size) allocates n*size bytes and initializes all bytes to zero. Both return void* and require free(). calloc is safer when you need zero-initialized memory."),
            ("What is a structure in C?",
             "A structure (struct) groups variables of different data types under one name. Example: struct Point { int x; int y; }; Access members with dot operator (p.x) or arrow for pointers (ptr->x). Unlike arrays, struct members can be different types."),
            ("What is the difference between local and global variables?",
             "Local variables are declared inside a function — exist only during function execution, stored on the stack, not accessible outside. Global variables are declared outside all functions — persist for the program's lifetime, stored in data segment, accessible from any function. Overuse of globals creates tight coupling."),
            ("What is a null pointer?",
             "A null pointer is a pointer that doesn't point to any valid memory location. In C, NULL is defined as (void*)0. Always initialize pointers to NULL when not assigned. Dereferencing a null pointer causes undefined behavior (segfault). Check if (ptr != NULL) before dereferencing."),
        ],
        "medium": [
            ("What is the difference between pass by value and pass by reference in C?",
             "C is pass-by-value only — function receives a copy of the argument. Changes don't affect the original. To simulate pass-by-reference, pass a pointer to the variable: void swap(int *a, int *b). The function then modifies the original through the pointer."),
            ("Explain dynamic memory allocation in C.",
             "Dynamic memory is allocated at runtime on the heap using: malloc() — uninitialized block; calloc() — zero-initialized; realloc() — resize existing block; free() — release memory. Always free allocated memory to prevent leaks. Check if malloc returns NULL (allocation failure)."),
            ("What are function pointers in C?",
             "Function pointers store the address of a function. Declaration: int (*fp)(int, int); Assignment: fp = add; Call: result = fp(3, 4). Used for callbacks, implementing polymorphism, jump tables. Example: qsort() takes a comparator function pointer."),
            ("What is the difference between struct and union?",
             "struct allocates separate memory for each member — total size is sum of all members (plus padding). union shares the same memory for all members — size equals the largest member. Only one union member holds a valid value at a time. Unions save memory when only one field is used at once."),
            ("What is a dangling pointer?",
             "A dangling pointer points to memory that has already been freed or gone out of scope. Accessing it causes undefined behavior — crashes or data corruption. Prevention: set pointer to NULL after free(); avoid returning addresses of local variables; use smart pointers in C++."),
        ],
        "hard": [
            ("Explain memory layout of a C program (stack, heap, BSS, data, text segments).",
             "Text: compiled machine code (read-only). Data: initialized global/static variables. BSS: uninitialized global/static variables (zero-initialized). Heap: dynamic memory (malloc/free), grows upward. Stack: function call frames, local variables, grows downward. Stack overflow occurs when recursion or large locals exhaust stack space."),
            ("What is volatile keyword in C and when to use it?",
             "volatile tells the compiler not to optimize reads/writes to a variable — always read from memory, never from cache/register. Use for: hardware registers, variables modified by ISR (interrupt service routines), shared variables in multi-threaded code (though volatile alone doesn't guarantee atomicity)."),
            ("Explain how linked list is implemented in C.",
             "A linked list node contains data and a pointer to the next node: struct Node { int data; struct Node* next; }; Head pointer marks the start. Traverse by following next pointers until NULL. Insert at head: newNode->next = head; head = newNode. O(n) access but O(1) insert/delete at known position."),
            ("What are bit fields in C?",
             "Bit fields allow specifying the exact number of bits a struct member occupies: struct Flags { unsigned int active: 1; unsigned int mode: 3; }; Saves memory when values have small ranges. Useful for hardware register mapping, protocol headers. Portability can vary across compilers."),
            ("What is the difference between #define and const in C?",
             "#define is a preprocessor macro — text substitution before compilation, no type checking, no scope, no memory. const declares a typed, scoped constant — has a memory location, supports type checking. Prefer const in C++ (always) and in C when you need type safety."),
        ],
    },

    "cpp": {
        "easy": [
            ("What is the difference between C and C++?",
             "C is procedural; C++ adds OOP (classes, inheritance, polymorphism), templates, STL, exceptions, references, and namespaces. C++ is a superset of C — most C code compiles as C++. C++ has stronger type checking and supports both low-level and high-level programming."),
            ("What is a class in C++?",
             "A class is a user-defined type combining data (member variables) and functions (member methods). Members are private by default. Objects are instances of a class. Classes support encapsulation, inheritance, and polymorphism. Example: class Dog { string name; void bark(); };"),
            ("What is the difference between struct and class in C++?",
             "Technically only one difference: struct members are public by default, class members are private by default. Convention: use struct for plain data (POD types), use class for objects with behavior and encapsulation. Both support inheritance, methods, and access specifiers."),
            ("What is a constructor and destructor?",
             "Constructor: special method called when object is created — same name as class, no return type, initializes member variables. Destructor: called when object goes out of scope or is deleted — ~ClassName(), releases resources. RAII pattern uses constructor/destructor for resource management."),
            ("What is function overloading in C++?",
             "Function overloading allows multiple functions with the same name but different parameter types or counts. The compiler selects the correct version at compile time based on argument types. Example: print(int), print(double), print(string) are three overloads. Return type alone cannot distinguish overloads."),
        ],
        "medium": [
            ("What is polymorphism in C++? Explain with example.",
             "Polymorphism means 'many forms'. Compile-time: function/operator overloading. Runtime: virtual functions — base class pointer calls derived class method. Example: Animal* a = new Dog(); a->speak(); calls Dog::speak() if speak() is virtual. Enables writing generic code that works with future derived types."),
            ("What is a virtual function in C++?",
             "A virtual function is declared with 'virtual' keyword in base class. When called via base pointer/reference, the derived class's version executes (dynamic dispatch). Pure virtual: virtual void f() = 0; makes class abstract. The vtable (virtual function table) enables runtime dispatch."),
            ("What is the difference between new/delete and malloc/free?",
             "malloc/free are C functions — allocate raw memory, don't call constructors/destructors. new/delete are C++ operators — call constructors on allocation and destructors on deallocation. new throws std::bad_alloc on failure; malloc returns NULL. Always pair new with delete and new[] with delete[]."),
            ("What are templates in C++?",
             "Templates allow writing generic code that works with any type, resolved at compile time. Function templates: template<typename T> T max(T a, T b). Class templates: template<typename T> class Stack. The compiler generates type-specific code for each instantiation. Foundation of STL containers and algorithms."),
            ("What is operator overloading?",
             "Operator overloading allows defining custom behavior for operators (+, -, ==, <<, etc.) for user-defined types. Example: Vector operator+(const Vector& v) enables v1 + v2. Makes code more intuitive. Some operators can't be overloaded: ::, .*, ., ?:. Overload with care — maintain expected semantics."),
        ],
        "hard": [
            ("What is the Rule of Three/Five in C++?",
             "Rule of Three: if you define any of destructor, copy constructor, copy assignment operator, you should define all three — they manage the same resource. Rule of Five (C++11): adds move constructor and move assignment operator for efficiency. Rule of Zero: prefer smart pointers/containers so you need none of them."),
            ("Explain move semantics and rvalue references in C++11.",
             "Move semantics transfer ownership of resources instead of copying — avoids expensive deep copies. Rvalue reference (&&) binds to temporaries. Move constructor/assignment 'steal' resources from the source. std::move() casts to rvalue, enabling moves. Critical for performance with containers of heap-allocated objects."),
            ("What is RAII and how does it work?",
             "RAII (Resource Acquisition Is Initialization) ties resource lifetime to object lifetime. Acquire resource in constructor, release in destructor. When object goes out of scope, destructor runs automatically — even if exception thrown. Examples: std::fstream, std::mutex (lock_guard), std::unique_ptr. Eliminates resource leaks."),
            ("What are smart pointers (unique_ptr, shared_ptr, weak_ptr)?",
             "unique_ptr: exclusive ownership, non-copyable, moves ownership with std::move, zero overhead. shared_ptr: shared ownership via reference counting, destroyed when count hits 0, some overhead. weak_ptr: non-owning reference to shared_ptr object, avoids circular reference memory leaks. Prefer these over raw new/delete."),
            ("Explain virtual dispatch and vtable mechanism.",
             "When a class has virtual functions, the compiler creates a vtable (array of function pointers). Each object with virtual functions has a hidden vptr pointing to its class's vtable. At runtime, calling a virtual function follows vptr → vtable → correct function. This enables runtime polymorphism with ~1 indirect call overhead."),
        ],
    },

    "oops": {
        "easy": [
            ("What are the four pillars of OOP?",
             "1. Encapsulation: bundling data and methods, hiding internal state. 2. Abstraction: exposing only essential features, hiding complexity. 3. Inheritance: creating new classes from existing ones, reusing code. 4. Polymorphism: same interface, different behavior depending on the object type."),
            ("What is the difference between a class and an object?",
             "A class is a blueprint/template defining attributes and methods — it exists in code. An object is an instance of a class — it exists in memory at runtime with actual values. Example: 'Car' is a class; your specific red Toyota with VIN 12345 is an object."),
            ("What is encapsulation?",
             "Encapsulation is bundling data (fields) and methods that operate on that data within a single unit (class), and restricting direct access to internal state using access modifiers (private, protected, public). Exposed via getters/setters. Benefits: data integrity, reduced coupling, easier maintenance."),
            ("What is inheritance and what are its types?",
             "Inheritance lets a child class acquire properties and behaviors of a parent class, promoting code reuse. Types: single (one parent), multilevel (chain), hierarchical (multiple children, one parent), multiple (multiple parents — supported in C++/Python, not Java), hybrid (combination). Use 'is-a' relationship."),
            ("What is the difference between method overloading and overriding?",
             "Overloading: same method name, different parameters in the same class — compile-time polymorphism. Overriding: subclass redefines parent's method with same signature — runtime polymorphism. Overloading changes the signature; overriding changes the implementation for a given signature."),
        ],
        "medium": [
            ("What is polymorphism? Explain runtime vs compile-time polymorphism.",
             "Polymorphism means one interface, many forms. Compile-time (static): resolved at compile time — method overloading, operator overloading, templates. Runtime (dynamic): resolved at runtime via virtual functions/method overriding — achieved through inheritance and base class pointers/references."),
            ("What is abstraction and how is it achieved?",
             "Abstraction hides complexity and shows only essential features. In OOP, achieved through: abstract classes (contain at least one abstract/pure virtual method, cannot be instantiated), interfaces (pure contracts with no implementation), and encapsulation. Users interact with what an object does, not how."),
            ("What is an interface and how is it different from an abstract class?",
             "Interface: pure contract — all methods abstract (no implementation), no state, a class can implement many. Abstract class: partial implementation — can have concrete methods, constructors, instance variables, a class can extend only one. Use interface for capability ('can fly'); abstract class for shared base behavior."),
            ("What is multiple inheritance and what problems does it cause?",
             "Multiple inheritance lets a class inherit from more than one parent. Problem: Diamond Problem — if two parents share a common ancestor, ambiguity arises about which grandparent's method to use. Java solves this by disallowing multiple class inheritance (but allows multiple interfaces). C++ uses virtual inheritance to resolve it."),
            ("What is the difference between composition and inheritance?",
             "Inheritance: 'is-a' relationship — Dog is an Animal. Subclass gets parent's behavior. Tight coupling; changes to parent affect children. Composition: 'has-a' relationship — Car has an Engine. Include objects as members. Loosely coupled; more flexible. Prefer composition over inheritance for flexibility (GoF principle)."),
        ],
        "hard": [
            ("Explain SOLID principles in detail with examples.",
             "S-Single Responsibility: one class, one reason to change. O-Open/Closed: extend behavior without modifying existing code (use interfaces). L-Liskov Substitution: subclasses must be substitutable for their base class without breaking the program. I-Interface Segregation: prefer small specific interfaces. D-Dependency Inversion: depend on abstractions, not concretions."),
            ("What is the diamond problem and how is it solved?",
             "Diamond problem: class D inherits from B and C, both inheriting from A. Which A implementation does D get? Ambiguity in method lookup. Solutions: Java — no multiple class inheritance, use interfaces; C++ — virtual inheritance (virtual keyword on B and C's inheritance from A) ensures only one copy of A exists in D."),
            ("What are design patterns? Explain Singleton and Factory pattern.",
             "Design patterns are reusable solutions to common design problems. Singleton: ensures only one instance of a class exists, provides global access point — used for logging, config, connection pools. Factory: defines an interface for creating objects but lets subclasses decide which class to instantiate — decouples client from concrete classes."),
            ("What is dependency injection?",
             "Dependency Injection (DI) is providing dependencies to a class from the outside rather than the class creating them. Types: constructor injection, setter injection, interface injection. Benefits: loose coupling, easier testing (inject mocks), follows Dependency Inversion principle. Used heavily in Spring, Angular, .NET frameworks."),
            ("Explain the Open/Closed Principle with a real-world example.",
             "Open/Closed: software entities should be open for extension but closed for modification. Example: payment system with PaymentProcessor class — don't modify it to add PayPal; instead create a PaymentMethod interface. PayPal implements PaymentMethod; processor uses the interface. Add new methods without changing existing code."),
        ],
    },

    "os": {
        "easy": [
            ("What is an operating system and what are its functions?",
             "An OS is system software managing hardware and software resources. Functions: process management (scheduling, synchronization), memory management (allocation, virtual memory), file system management, I/O device management, security/access control, networking. Acts as interface between user and hardware."),
            ("What is the difference between a process and a thread?",
             "Process: independent program in execution with its own memory space (code, heap, stack, file handles). Thread: lightweight unit of execution within a process, sharing the process's memory and resources. Context switching between processes is expensive; between threads is cheaper. Threads share data easily but risk race conditions."),
            ("What is context switching?",
             "Context switching is saving the state (registers, PC, stack pointer, memory maps) of the current running process/thread and loading the saved state of another to run. Enables time-sharing and multitasking. The PCB (Process Control Block) stores the context. Overhead: time to save/restore + cache flush."),
            ("What is a deadlock?",
             "Deadlock is a state where a set of processes are permanently blocked, each waiting for a resource held by another in the set. Four necessary conditions (Coffman): Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait. All four must hold simultaneously for deadlock to occur."),
            ("What is virtual memory?",
             "Virtual memory allows processes to use more memory than physically available by using disk space as an extension of RAM. Each process gets its own virtual address space. The OS maps virtual addresses to physical addresses via page tables. Enables process isolation, simplifies programming, supports larger address spaces than physical RAM."),
        ],
        "medium": [
            ("What are the conditions for deadlock? How can it be prevented?",
             "Four Coffman conditions: Mutual Exclusion (resource held by one process), Hold & Wait (holding one resource while waiting for another), No Preemption (resources can't be forcibly taken), Circular Wait (circular chain of waiting processes). Prevention: break any one condition — e.g., order resource acquisition (eliminates circular wait)."),
            ("Explain process scheduling algorithms (FCFS, SJF, Round Robin).",
             "FCFS (First Come First Served): simple, non-preemptive, convoy effect. SJF (Shortest Job First): optimal average waiting time, requires knowing burst time, starvation risk. Round Robin: each process gets a fixed time quantum, preemptive, fair, suitable for time-sharing. Priority Scheduling: highest priority runs first, risk of starvation (use aging)."),
            ("What is the difference between paging and segmentation?",
             "Paging: divides memory into fixed-size pages; eliminates external fragmentation, may have internal fragmentation; transparent to programmer. Segmentation: divides into variable-size logical segments (code, stack, data); matches programmer's view; may cause external fragmentation. Modern systems use segmented paging."),
            ("What is thrashing in operating systems?",
             "Thrashing occurs when a process spends more time swapping pages in/out than executing — CPU utilization drops drastically. Caused by too many processes competing for limited frames. Solutions: reduce degree of multiprogramming, use working set model (keep frequently-used pages), apply page fault frequency algorithm."),
            ("What are semaphores and mutexes?",
             "Semaphore: integer variable for process synchronization. Binary semaphore (0/1) works like a mutex. Counting semaphore manages N identical resources. wait()/P() decrements; signal()/V() increments. Mutex (Mutual Exclusion): binary lock, only the thread that locked it can unlock it. Ownership matters in mutex, not in semaphore."),
        ],
        "hard": [
            ("Explain the banker's algorithm for deadlock avoidance.",
             "Banker's algorithm checks if granting a resource request leaves the system in a 'safe state' — a state where all processes can eventually complete. It simulates allocation and checks if a safe sequence exists (an order in which each process can get max needed resources). If safe: grant; else: make process wait. Named after bank loan analogy."),
            ("What is the difference between internal and external fragmentation?",
             "Internal fragmentation: wasted space inside an allocated memory block — e.g., process needs 18KB but gets 20KB page; 2KB wasted. Caused by fixed-size allocation. External fragmentation: enough total free memory exists but it's scattered in non-contiguous blocks, so a large request can't be fulfilled. Compaction resolves external fragmentation."),
            ("Explain page replacement algorithms (LRU, FIFO, Optimal).",
             "FIFO: evict oldest-loaded page — simple but suffers Belady's anomaly (more frames → more faults). LRU (Least Recently Used): evict page not used longest — good practical performance, approximated with clock algorithm. Optimal: evict page used farthest in future — theoretically best, impossible in practice (need future knowledge), used as benchmark."),
            ("What is inter-process communication (IPC)? Explain its mechanisms.",
             "IPC allows processes to communicate and share data. Mechanisms: Pipes (unidirectional, parent-child); Named Pipes/FIFOs (bidirectional, unrelated processes); Message Queues (kernel-managed queue); Shared Memory (fastest — processes map same physical pages, need synchronization); Sockets (network or local); Signals (async notifications)."),
            ("Explain the concept of spinlock vs mutex.",
             "Spinlock: thread repeatedly checks (spins/busy-waits) if lock is available — no context switch, wastes CPU, good for very short critical sections on multi-core. Mutex: thread blocks (goes to sleep) if lock unavailable — OS wakes it when lock is released, involves context switch overhead. Use spinlock for microsecond-level waits; mutex for longer waits."),
        ],
    },

    "cn": {
        "easy": [
            ("What is the OSI model? Name all 7 layers.",
             "OSI (Open Systems Interconnection) has 7 layers: 1-Physical (bits, cables), 2-Data Link (frames, MAC addresses, error detection), 3-Network (IP routing, logical addressing), 4-Transport (TCP/UDP, end-to-end delivery), 5-Session (connection management), 6-Presentation (encryption, encoding), 7-Application (HTTP, FTP, DNS, user-facing protocols)."),
            ("What is the difference between TCP and UDP?",
             "TCP (Transmission Control Protocol): connection-oriented (3-way handshake), reliable (acknowledgments, retransmission), ordered delivery, flow control and congestion control, higher overhead — used for HTTP, FTP, email. UDP (User Datagram Protocol): connectionless, no reliability guarantees, no ordering, low overhead, fast — used for DNS, video streaming, gaming, VoIP."),
            ("What is an IP address?",
             "An IP address is a unique numerical identifier for a device on a network. IPv4: 32-bit, written as 4 octets (e.g., 192.168.1.1), ~4.3 billion addresses. IPv6: 128-bit, written in hex (e.g., 2001:db8::1), virtually unlimited. Used by routers to route packets between networks."),
            ("What is DNS and how does it work?",
             "DNS (Domain Name System) translates domain names to IP addresses. Process: 1. Browser checks local cache. 2. Queries recursive resolver (ISP). 3. Resolver queries root nameserver (knows TLD servers). 4. Queries TLD server (.com). 5. Queries authoritative nameserver for domain. 6. Returns IP. Result cached with TTL."),
            ("What is the difference between HTTP and HTTPS?",
             "HTTP (HyperText Transfer Protocol): plain text communication, port 80, no encryption — data can be intercepted. HTTPS (HTTP Secure): HTTP over TLS/SSL, port 443, encrypts data in transit, authenticates server via certificate, prevents MITM attacks. All modern websites should use HTTPS."),
        ],
        "medium": [
            ("What is the TCP three-way handshake?",
             "TCP establishes connection via 3-way handshake: 1. Client sends SYN (synchronize) with initial sequence number. 2. Server responds SYN-ACK (synchronize-acknowledge) with its own sequence number. 3. Client sends ACK (acknowledge). Connection established. Termination uses 4-way FIN handshake. Ensures both sides are ready to communicate."),
            ("What is the difference between IPv4 and IPv6?",
             "IPv4: 32-bit (4 bytes), ~4.3 billion addresses (exhausted), NAT used to extend it, header: 20 bytes, decimal notation. IPv6: 128-bit, 340 undecillion addresses, built-in IPsec, no NAT needed, simplified header: 40 bytes, hex notation, stateless address autoconfiguration (SLAAC), eliminates broadcast (uses multicast)."),
            ("What is subnetting and CIDR notation?",
             "Subnetting divides a network into smaller sub-networks for better organization and security. CIDR (Classless Inter-Domain Routing) notation: IP/prefix-length, e.g., 192.168.1.0/24 means first 24 bits are network, last 8 are hosts (256 addresses, 254 usable). /24 = subnet mask 255.255.255.0."),
            ("What is a firewall and how does it work?",
             "A firewall filters network traffic based on rules — blocks or allows packets based on source/destination IP, port, protocol, and state. Types: packet filtering (stateless, checks individual packets), stateful inspection (tracks connection state), application-layer (DPI, understands protocols). Protects networks from unauthorized access."),
            ("Explain the difference between routing and switching.",
             "Switching (Layer 2): forwards frames within same network based on MAC addresses — switches maintain MAC address tables. Routing (Layer 3): forwards packets between different networks based on IP addresses — routers maintain routing tables with paths. Switching is faster; routing enables inter-network communication."),
        ],
        "hard": [
            ("Explain TCP congestion control mechanisms.",
             "TCP congestion control prevents overwhelming the network: Slow Start — cwnd starts at 1 MSS, doubles each RTT until ssthresh. Congestion Avoidance — linear growth after ssthresh. Fast Retransmit — resend after 3 duplicate ACKs without waiting for timeout. Fast Recovery — halve cwnd instead of restarting slow start. Algorithms: Reno, CUBIC (Linux default), BBR."),
            ("What is BGP and how does it work?",
             "BGP (Border Gateway Protocol) is the internet's routing protocol — routes between Autonomous Systems (AS). Path vector protocol: advertises complete AS paths to prevent loops. eBGP (between ASes) and iBGP (within AS). Routers exchange UPDATE messages with network prefixes and AS paths. Policy-based routing: ISPs control traffic flow via route manipulation."),
            ("Explain SSL/TLS handshake in detail.",
             "TLS 1.3 handshake: 1. Client Hello (TLS version, cipher suites, random). 2. Server Hello (chosen cipher, certificate, random). 3. Client verifies certificate against CA. 4. Key exchange (ECDHE). 5. Both derive session keys from shared secret. 6. Finished messages (MAC verification). Data encrypted with symmetric key. ~1 RTT in TLS 1.3."),
            ("What is NAT and why is it used?",
             "NAT (Network Address Translation) maps private IP addresses to a public IP for internet communication. Router rewrites source IP in outgoing packets and tracks mappings to forward replies correctly. Purpose: conserves public IPv4 addresses (multiple devices share one public IP), adds a layer of security by hiding internal topology. Types: static, dynamic, PAT (Port Address Translation/overload)."),
            ("Explain the difference between distance vector and link state routing.",
             "Distance Vector (RIP): each router knows cost to neighbors, shares routing table with neighbors periodically, Bellman-Ford algorithm, slow convergence, count-to-infinity problem. Link State (OSPF): each router knows full topology, floods link state advertisements to all, Dijkstra's algorithm, fast convergence, scalable, high memory/CPU usage."),
        ],
    },

    "dbms": {
        "easy": [
            ("What is a database and what is DBMS?",
             "A database is an organized collection of structured data stored electronically. A DBMS (Database Management System) is software that manages databases — provides interfaces to create, read, update, delete data, handles concurrency, security, backup, and recovery. Examples: MySQL, PostgreSQL, Oracle, MongoDB."),
            ("What is the difference between SQL and NoSQL?",
             "SQL (relational): structured schema, tables with rows/columns, ACID transactions, strong consistency, vertical scaling — MySQL, PostgreSQL. NoSQL: flexible schema (document, key-value, graph, column), horizontal scaling, eventual consistency, designed for large-scale distributed data — MongoDB, Cassandra, Redis. Choose based on data structure and scale needs."),
            ("What are primary key and foreign key?",
             "Primary key: uniquely identifies each row in a table — cannot be NULL, must be unique. A table has one PK (can be composite). Foreign key: column(s) in one table referencing the primary key of another table — enforces referential integrity. Prevents orphaned records. Example: Orders.customer_id references Customers.id."),
            ("What is normalization?",
             "Normalization is organizing a database to reduce redundancy and improve integrity. Process of decomposing tables to remove anomalies (insertion, update, deletion). Normal forms: 1NF (atomic values, no repeating groups), 2NF (no partial dependency), 3NF (no transitive dependency), BCNF. Higher NF = less redundancy but more joins."),
            ("What is the difference between DELETE, TRUNCATE, and DROP?",
             "DELETE: DML — removes specific rows with WHERE clause, can be rolled back, triggers fire, logs each row deletion, slow for large data. TRUNCATE: DDL — removes all rows, faster (deallocates pages), minimal logging, cannot use WHERE, resets identity, usually can't be rolled back. DROP: DDL — removes entire table including structure, indexes, and data permanently."),
        ],
        "medium": [
            ("What are the ACID properties in a database?",
             "ACID ensures reliable transactions: Atomicity — transaction is all-or-nothing; if any part fails, entire transaction rolls back. Consistency — transaction brings DB from one valid state to another. Isolation — concurrent transactions don't interfere with each other. Durability — committed transactions persist even after system failure (WAL/redo logs)."),
            ("Explain the different normal forms (1NF, 2NF, 3NF, BCNF).",
             "1NF: each column has atomic values, no repeating groups, each row unique. 2NF: 1NF + no partial dependency (non-key attributes depend on full PK, relevant for composite PKs). 3NF: 2NF + no transitive dependency (non-key attributes depend only on PK, not on other non-key attributes). BCNF: 3NF + every determinant is a candidate key."),
            ("What is an index and how does it improve performance?",
             "An index is a data structure (B-tree or hash) on one or more columns that speeds up data retrieval. Without index: full table scan O(n). With index: O(log n) for B-tree. Trade-off: speeds up reads but slows INSERT/UPDATE/DELETE (index must be maintained). Create indexes on frequently-queried, high-cardinality columns used in WHERE/JOIN/ORDER BY."),
            ("What is a JOIN? Explain types of JOINs.",
             "JOIN combines rows from two or more tables based on a related column. Types: INNER JOIN — only matching rows from both tables. LEFT JOIN — all rows from left + matching from right (NULL if no match). RIGHT JOIN — all rows from right + matching from left. FULL OUTER JOIN — all rows from both. CROSS JOIN — cartesian product. SELF JOIN — table joined with itself."),
            ("What is a transaction and how is it managed?",
             "A transaction is a unit of work that must execute completely or not at all. Managed via: BEGIN/START TRANSACTION, COMMIT (save changes), ROLLBACK (undo changes). Savepoints allow partial rollback. Isolation levels (READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE) control concurrency. WAL (Write-Ahead Logging) ensures durability."),
        ],
        "hard": [
            ("What is the difference between clustered and non-clustered index?",
             "Clustered index: defines physical order of data in the table — rows stored sorted by index key. Only one per table (usually PK). Data pages ARE the index leaf level. Fast range queries. Non-clustered index: separate structure from data — leaf nodes contain index key + pointer (row locator) to actual data. Multiple allowed per table. Extra lookup step needed."),
            ("Explain deadlock in databases and how to handle it.",
             "DB deadlock: two transactions each hold a lock the other needs. Example: T1 locks A then waits for B; T2 locks B then waits for A. Detection: wait-for graph cycle detection. Resolution: DB chooses a victim (rollback one transaction). Prevention: consistent lock ordering, timeout-based rollback, optimistic concurrency control, reduce transaction scope."),
            ("What is query optimization? How does a query planner work?",
             "Query optimizer transforms SQL into an efficient execution plan. Steps: parsing → logical plan (relational algebra) → plan enumeration (consider join orders, access methods) → cost estimation (statistics: row counts, histograms, index stats) → choose minimum-cost plan. EXPLAIN/EXPLAIN ANALYZE shows the chosen plan. Update statistics for accurate cost estimates."),
            ("Explain the CAP theorem.",
             "CAP theorem: a distributed system can guarantee at most two of three: Consistency (all nodes see same data simultaneously), Availability (every request gets a response), Partition Tolerance (system works despite network partition). Network partitions are unavoidable, so choose CP (consistent + partition-tolerant: HBase, Zookeeper) or AP (available + partition-tolerant: Cassandra, DynamoDB)."),
            ("What is database sharding and when should you use it?",
             "Sharding horizontally partitions data across multiple database servers (shards), each holding a subset. Shard key determines which shard stores each row. Benefits: horizontal scalability, improved performance. Challenges: cross-shard queries (expensive), rebalancing when adding shards, maintaining ACID across shards. Use when single-server vertical scaling is insufficient."),
        ],
    },

    "sql": {
        "easy": [
            ("What is the difference between WHERE and HAVING clause?",
             "WHERE filters rows before grouping — operates on individual rows, cannot use aggregate functions. HAVING filters groups after GROUP BY — operates on aggregated results, can use aggregate functions (SUM, COUNT, AVG). Example: WHERE salary > 50000 filters employees; HAVING AVG(salary) > 50000 filters departments by average salary."),
            ("What is the difference between UNION and UNION ALL?",
             "UNION combines result sets from two SELECT queries and removes duplicate rows (performs a DISTINCT operation) — slower due to deduplication. UNION ALL combines result sets and keeps all rows including duplicates — faster. Both require same number of columns and compatible data types. Use UNION ALL when duplicates are acceptable or impossible."),
            ("What are aggregate functions in SQL?",
             "Aggregate functions perform calculations on a set of values and return a single value. Common: COUNT(*) — total rows, COUNT(col) — non-NULL values; SUM(col); AVG(col); MIN(col); MAX(col). Used with GROUP BY to aggregate per group. NULL values are ignored (except COUNT(*)). Used in SELECT and HAVING clauses."),
            ("What is a VIEW in SQL?",
             "A VIEW is a virtual table defined by a stored SELECT query. Doesn't store data itself — executes the underlying query each time. Benefits: simplifies complex queries, provides security (restrict column/row access), encapsulates logic. Updatable views exist but have restrictions. Materialized views (PostgreSQL) store results physically for performance."),
            ("What is the difference between CHAR and VARCHAR?",
             "CHAR(n): fixed-length, always stores exactly n characters (pads with spaces if shorter) — faster for fixed-length data like country codes. VARCHAR(n): variable-length, stores only actual characters + length overhead — saves space for variable data. Use CHAR for data with consistent length; VARCHAR for variable-length strings like names, emails."),
        ],
        "medium": [
            ("Write a query to find the second highest salary from an employee table.",
             "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees); Or using DENSE_RANK: SELECT salary FROM (SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) as rnk FROM employees) t WHERE rnk = 2; DENSE_RANK handles ties correctly — both tied employees at rank 1 still give a rank 2."),
            ("What are window functions in SQL? Give an example.",
             "Window functions perform calculations across a set of rows related to the current row without collapsing rows (unlike GROUP BY). Syntax: FUNCTION() OVER (PARTITION BY col ORDER BY col ROWS/RANGE ...). Examples: ROW_NUMBER(), RANK(), DENSE_RANK(), LAG(), LEAD(), SUM() OVER(...), AVG() OVER(...). Example: SELECT name, salary, RANK() OVER (PARTITION BY dept ORDER BY salary DESC) as rank FROM employees;"),
            ("What is a stored procedure and how is it different from a function?",
             "Stored procedure: precompiled SQL block, can have IN/OUT/INOUT parameters, can modify data (INSERT/UPDATE/DELETE), called with EXEC/CALL, can return multiple result sets, can use transactions. Function: returns a single value or table, used in SELECT/WHERE, cannot modify data (generally), no OUT parameters. Use procedures for complex operations; functions for reusable calculations."),
            ("Explain different types of JOINs with examples.",
             "INNER JOIN: SELECT * FROM A JOIN B ON A.id = B.aid — only matching rows. LEFT JOIN: all A rows + matching B (NULL if no B match) — keeps all left records. RIGHT JOIN: all B rows + matching A. FULL OUTER JOIN: all rows from both, NULL where no match. CROSS JOIN: every A row paired with every B row (cartesian product). SELF JOIN: employee JOIN employee ON e.manager_id = m.id."),
            ("What are triggers in SQL?",
             "Triggers are stored programs that automatically execute in response to DML events (INSERT, UPDATE, DELETE) on a table. Types: BEFORE trigger (validate/modify before change), AFTER trigger (audit log after change), INSTEAD OF trigger (on views). Use cases: audit logging, enforcing complex business rules, automatically updating derived columns. Can cause performance issues if overused."),
        ],
        "hard": [
            ("Explain query execution plan and how to optimize slow queries.",
             "Execution plan shows how DB engine runs a query: table scans vs index seeks, join methods (nested loop, hash join, merge join), estimated vs actual rows. Use EXPLAIN/EXPLAIN ANALYZE. Optimization: add appropriate indexes (cover WHERE/JOIN/ORDER BY columns), avoid SELECT *, rewrite correlated subqueries as JOINs, update statistics, avoid functions on indexed columns in WHERE."),
            ("What is the difference between correlated and non-correlated subqueries?",
             "Non-correlated subquery: executes once independently, result used by outer query. Example: WHERE salary > (SELECT AVG(salary) FROM emp). Correlated subquery: references outer query, executes once per row of outer query — O(n) executions. Example: WHERE salary > (SELECT AVG(salary) FROM emp e2 WHERE e2.dept = e1.dept). Correlated is slower; often rewritable as JOIN."),
            ("Explain partitioning in SQL databases.",
             "Partitioning divides large tables into smaller physical pieces (partitions) while appearing as one table. Types: Range (dates, IDs), List (specific values like country), Hash (even distribution), Composite. Benefits: faster queries (partition pruning), easier archiving, parallel operations. Each partition is an independent segment. Partition key must be in WHERE for pruning to work."),
            ("Write a query to find duplicate records and delete them keeping one.",
             "Find duplicates: SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1; Delete keeping lowest ID: DELETE FROM users WHERE id NOT IN (SELECT MIN(id) FROM users GROUP BY email); Or with CTE: WITH cte AS (SELECT id, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rn FROM users) DELETE FROM cte WHERE rn > 1;"),
            ("What are CTEs (Common Table Expressions) and recursive CTEs?",
             "CTE: named temporary result set defined with WITH clause, usable in the same query. Improves readability vs subqueries. WITH sales AS (SELECT ...) SELECT * FROM sales WHERE ... Recursive CTE: references itself to traverse hierarchical data (org charts, trees, paths). Structure: anchor member (base case) UNION ALL recursive member (references CTE). Example: traverse employee hierarchy from CEO down."),
        ],
    },

    "mix": {
        "easy": [
            ("What is the difference between a stack and a queue?",
             "Stack: LIFO (Last In First Out) — push/pop from the same end (top). Used for function calls, undo operations, expression evaluation. Queue: FIFO (First In First Out) — enqueue at rear, dequeue from front. Used for BFS, scheduling, print spoolers. Both are abstract data types implementable with arrays or linked lists."),
            ("What is recursion? Give an example.",
             "Recursion is a function calling itself to solve a smaller version of the same problem. Must have a base case (stops recursion) and recursive case. Example: factorial(n) = n * factorial(n-1), base: factorial(0) = 1. Used for tree traversal, divide and conquer. Stack overflow occurs if base case is missing or recursion is too deep."),
            ("What is the difference between compiled and interpreted languages?",
             "Compiled: source code translated to machine code once by a compiler before execution — fast runtime (C, C++, Go, Rust). Interpreted: code executed line-by-line by an interpreter at runtime — flexible, easier debugging, slower (Python, JavaScript, Ruby). Hybrid: compiled to intermediate bytecode then interpreted/JIT compiled (Java, C#, Python bytecode)."),
            ("What is an API?",
             "API (Application Programming Interface) is a set of rules/protocols for how software components communicate. Defines requests, data formats, and responses. Types: REST (HTTP-based, stateless), SOAP, GraphQL, gRPC. Example: Twitter API lets apps post tweets programmatically. Enables integration between different systems without exposing internal implementation."),
            ("What is the difference between synchronous and asynchronous programming?",
             "Synchronous: operations execute sequentially — each waits for the previous to complete before starting. Simple but blocks execution. Asynchronous: operations can start without waiting for previous to finish — uses callbacks, promises, async/await. Non-blocking, better for I/O-bound tasks. Example: async HTTP requests don't block UI while waiting for server response."),
        ],
        "medium": [
            ("What is the difference between REST and GraphQL?",
             "REST: multiple fixed endpoints (GET /users, GET /users/1/posts), over-fetching (too much data) or under-fetching (multiple requests needed), versioned APIs. GraphQL: single endpoint, client specifies exact data needed in query, no over/under-fetching, strongly typed schema, better for complex/nested data. REST simpler; GraphQL more flexible for complex frontends."),
            ("Explain time complexity and Big-O notation.",
             "Big-O notation describes worst-case growth rate of an algorithm as input size n grows. Common: O(1) constant (hash lookup), O(log n) logarithmic (binary search), O(n) linear (array scan), O(n log n) (merge sort), O(n²) quadratic (bubble sort), O(2^n) exponential (subset enumeration). Helps compare algorithms independent of hardware."),
            ("What is the difference between SQL and NoSQL databases?",
             "SQL: relational, fixed schema, ACID transactions, vertical scaling, powerful querying with joins — PostgreSQL, MySQL. NoSQL: flexible schema (document/key-value/graph/wide-column), eventual consistency, horizontal scaling — MongoDB (document), Redis (key-value), Cassandra (wide-column), Neo4j (graph). Choose SQL for complex transactions; NoSQL for scale and flexible data."),
            ("What is a hash table and how does it work?",
             "A hash table stores key-value pairs for O(1) average-case lookup. Hash function maps key to an array index. Collisions (two keys same index) resolved by: chaining (linked list at each slot) or open addressing (probe for next empty slot). Load factor = entries/slots; rehash when too high. Used for: dictionaries, caches, sets, database indexes."),
            ("What is the difference between authentication and authorization?",
             "Authentication: verifying identity — 'who are you?' (username/password, biometric, JWT token). Authorization: verifying permissions — 'what can you do?' (role-based access, permissions, scopes). Authentication comes first. Example: logging into a bank is authentication; being allowed to view only your account is authorization. OAuth handles authorization; OpenID Connect adds authentication."),
        ],
        "hard": [
            ("Explain the CAP theorem and its implications.",
             "CAP: distributed systems can guarantee at most 2 of: Consistency (all nodes return same data), Availability (every request gets response), Partition Tolerance (works despite network splits). Since partitions happen in real networks, choose CP (HBase, Zookeeper — consistent but may reject requests during partition) or AP (Cassandra, DynamoDB — always responds but may return stale data)."),
            ("What is consistent hashing and where is it used?",
             "Consistent hashing maps both nodes and keys to a ring (circle of hash values). A key maps to the nearest node clockwise. Adding/removing a node only remaps keys from adjacent neighbors — minimizes redistribution (O(K/N) keys moved vs O(K) in modulo hashing). Used in distributed caches (Memcached), load balancers, distributed storage (Amazon DynamoDB, Cassandra)."),
            ("Design a URL shortener system.",
             "Components: Web servers (handle redirects), Key Generation Service (creates short codes — base62 of unique counter or hash), Database (maps short code → long URL with metadata), Cache (Redis for hot URLs). Flow: POST long URL → generate unique 6-7 char code → store mapping → return short URL. On access: lookup code in cache → DB → 301/302 redirect. Handle: expiration, analytics, custom slugs."),
            ("Explain the differences between monolithic and microservices architecture.",
             "Monolithic: single deployable unit with all functionality — simple to develop initially, hard to scale/maintain as it grows, one failure can bring down all. Microservices: independent services per business capability, each with own DB, communicate via API/message queue — independent deployment and scaling, technology flexibility, but: network overhead, distributed systems complexity, operational overhead."),
            ("What is eventual consistency?",
             "Eventual consistency is a consistency model for distributed systems: if no new updates are made to a given data item, all replicas will eventually converge to the same value. Reads may return stale data temporarily. Enables high availability and performance. Used by DNS, Amazon S3, DynamoDB. Contrast with strong consistency (reads always reflect latest write) which requires coordination overhead."),
        ],
    },
}


def generate_questions(subject, difficulty, count=5):
    subject = subject.lower()
    difficulty = difficulty.lower()
    if subject not in qa_db or difficulty not in qa_db[subject]:
        return []
    pool = [q for q, _ in qa_db[subject][difficulty]]
    if count <= len(pool):
        return random.sample(pool, count)
    result = []
    while len(result) < count:
        shuffled = pool[:]
        random.shuffle(shuffled)
        result.extend(shuffled)
    return result[:count]


def get_solution_for_question(question: str) -> str:
    for subject in qa_db.values():
        for difficulty in subject.values():
            for q, a in difficulty:
                if q == question:
                    return a
    return "Solution not found for this question."
